-- ============================================================
-- EticaDigital - Schema SQL para Supabase
-- Ejecutar en el Editor SQL de la consola de Supabase
-- ============================================================

-- 1. Tabla de Perfiles Públicos (Extensión de auth.users de Supabase)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    avatar_url TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Perfiles son visibles para todos" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Usuarios pueden editar su propio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger para crear un perfil público automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, avatar_url)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', 'usuario_' || substring(new.id::text from 1 for 8)),
        COALESCE(new.raw_user_meta_data->>'avatar_url', 'https://api.dicebear.com/7.x/bottts/svg?seed=' || new.id::text)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. Tabla de Categorías
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    icono TEXT DEFAULT 'Globe'
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categorías son visibles para todos" ON public.categories FOR SELECT USING (true);


-- 3. Tabla de Publicaciones (Posts)
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    contenido TEXT NOT NULL,
    autor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    categoria_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    es_bot BOOLEAN DEFAULT FALSE NOT NULL,
    votos_positivos INTEGER DEFAULT 0 NOT NULL,
    votos_negativos INTEGER DEFAULT 0 NOT NULL,
    imagen_url TEXT
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Posts son visibles para todos" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Usuarios autenticados pueden crear posts" ON public.posts FOR INSERT WITH CHECK (auth.uid() = autor_id OR es_bot = true);
CREATE POLICY "Autores pueden editar sus posts" ON public.posts FOR UPDATE USING (auth.uid() = autor_id);
CREATE POLICY "Autores pueden eliminar sus posts" ON public.posts FOR DELETE USING (auth.uid() = autor_id);


-- 4. Tabla de Comentarios
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenido TEXT NOT NULL,
    autor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    comentario_padre_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Comentarios son visibles para todos" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Usuarios autenticados pueden comentar" ON public.comments FOR INSERT WITH CHECK (auth.uid() = autor_id);
CREATE POLICY "Autores pueden editar sus comentarios" ON public.comments FOR UPDATE USING (auth.uid() = autor_id);


-- 5. Tabla de Votos
CREATE TABLE public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    tipo TEXT CHECK (tipo IN ('positivo', 'negativo')) NOT NULL,
    CONSTRAINT unique_user_post_vote UNIQUE (usuario_id, post_id)
);

ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Votos son visibles para todos" ON public.votes FOR SELECT USING (true);
CREATE POLICY "Usuarios autenticados pueden votar" ON public.votes FOR INSERT WITH CHECK (auth.uid() = usuario_id);
CREATE POLICY "Usuarios pueden cambiar su voto" ON public.votes FOR UPDATE USING (auth.uid() = usuario_id);
CREATE POLICY "Usuarios pueden retirar su voto" ON public.votes FOR DELETE USING (auth.uid() = usuario_id);

-- Trigger para recalcular votos en posts
CREATE OR REPLACE FUNCTION public.recalculate_post_votes()
RETURNS TRIGGER AS $$
DECLARE
    v_post_id BIGINT;
    pos_count INTEGER;
    neg_count INTEGER;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        v_post_id := OLD.post_id;
    ELSE
        v_post_id := NEW.post_id;
    END IF;

    SELECT COUNT(*) INTO pos_count FROM public.votes WHERE post_id = v_post_id AND tipo = 'positivo';
    SELECT COUNT(*) INTO neg_count FROM public.votes WHERE post_id = v_post_id AND tipo = 'negativo';

    UPDATE public.posts
    SET votos_positivos = pos_count,
        votos_negativos = neg_count
    WHERE id = v_post_id;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER update_post_votes_on_change
    AFTER INSERT OR UPDATE OR DELETE ON public.votes
    FOR EACH ROW EXECUTE FUNCTION public.recalculate_post_votes();


-- 6. Tabla de Auditorías de Proyectos
CREATE TABLE public.proyectos_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    nombre_proyecto TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    stack_tecnologico TEXT NOT NULL,
    score_cumplimiento INTEGER DEFAULT 100 NOT NULL,
    dictamen TEXT CHECK (dictamen IN ('viable', 'con_riesgos', 'no_viable')) DEFAULT 'viable' NOT NULL,
    analisis_cualitativo_ia TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.proyectos_auditoria ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus propias auditorías" ON public.proyectos_auditoria FOR SELECT USING (auth.uid() = usuario_id);
CREATE POLICY "Cualquiera puede crear auditorías" ON public.proyectos_auditoria FOR INSERT WITH CHECK (true);


-- 7. Tabla de Riesgos Detectados en Auditorías
CREATE TABLE public.riesgos_detectados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auditoria_id BIGINT REFERENCES public.proyectos_auditoria(id) ON DELETE CASCADE NOT NULL,
    titulo TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    gravedad TEXT CHECK (gravedad IN ('critica', 'media', 'leve')) NOT NULL,
    principio_ley_afectada TEXT NOT NULL,
    sugerencia_mitigacion TEXT
);

ALTER TABLE public.riesgos_detectados ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Riesgos visibles si la auditoría es del usuario" ON public.riesgos_detectados
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.proyectos_auditoria
            WHERE id = riesgos_detectados.auditoria_id AND usuario_id = auth.uid()
        )
    );
CREATE POLICY "Insertar riesgos al crear auditoría" ON public.riesgos_detectados FOR INSERT WITH CHECK (true);


-- ============================================================
-- SEED DATA: Categorías iniciales del foro
-- ============================================================
INSERT INTO public.categories (nombre, slug, descripcion, icono) VALUES
('Privacidad', 'privacidad', 'Espacio dedicado al debate e información sobre Privacidad de datos personales y legislación.', 'EyeOff'),
('Inteligencia Artificial', 'inteligencia-artificial', 'Espacio dedicado al debate e información sobre IA responsable, sesgos algorítmicos y ética en ML.', 'Brain'),
('Ciberseguridad', 'ciberseguridad', 'Espacio dedicado al debate e información sobre amenazas, vulnerabilidades y defensa digital.', 'Shield'),
('Derechos Digitales', 'derechos-digitales', 'Espacio dedicado al debate e información sobre libertad de expresión, censura y gobernanza digital.', 'Globe'),
('Propiedad Intelectual', 'propiedad-intelectual', 'Espacio dedicado al debate e información sobre derechos de autor, licencias y fair use en la era digital.', 'Copyright')
ON CONFLICT (nombre) DO NOTHING;


-- ============================================================
-- SEED DATA: Posts iniciales de los bots
-- ============================================================
INSERT INTO public.posts (titulo, contenido, autor_id, categoria_id, es_bot) VALUES
(
    'Dilema Ético Semanal: ¿Algoritmos imparciales? El sesgo en el reclutamiento de personal',
    E'Una empresa multinacional decide delegar su primer filtro de contratación de ingenieros a una Inteligencia Artificial. Al cabo de unos meses, se descubre que el sistema ha descartado sistemáticamente candidatas mujeres para puestos técnicos porque se entrenó con currículums históricos de los últimos 20 años, donde el 90% de los contratados eran hombres. El sistema asumió que ser hombre era un factor de éxito.\n\n**Pregunta para debate:** Como líder del equipo de TI, tu dirección te pide mantener el sistema activo argumentando que ahorra millones de dólares y que ''se auto-corregirá con el tiempo''. ¿Qué harías? ¿Apagarías el sistema inmediatamente arriesgando tu puesto, o aceptarías el sesgo en favor del negocio?',
    NULL,
    (SELECT id FROM public.categories WHERE slug = 'inteligencia-artificial'),
    true
),
(
    'Europa multa a una red social con 400 millones por violar la privacidad infantil',
    E'Un organismo regulador europeo ha impuesto una multa multimillonaria a una conocida plataforma social al descubrirse que utilizaba algoritmos de recomendación que explotaban perfiles conductuales de menores de edad sin consentimiento explícito de sus padres. Además, las cuentas de los menores eran públicas por defecto.\n\n**Análisis:** Este caso reaviva el debate sobre el diseño de productos digitales éticos y la necesidad de priorizar la privacidad infantil sobre el engagement comercial.\n\n[Fuente Simulada: El Diario de Ética Digital](https://example.com/noticia-privacidad-menores)',
    NULL,
    (SELECT id FROM public.categories WHERE slug = 'privacidad'),
    true
),
(
    'Dilema Ético Semanal: El dilema del ransomware en un hospital infantil',
    E'Un hospital pediátrico sufre un ciberataque de ransomware que cifra todos los historiales médicos electrónicos y sistemas de monitoreo en tiempo real. Los ciberdelincuentes exigen un rescate en criptomonedas equivalente a $150,000 USD para entregar la clave de descifrado, y amenazan con borrarlo todo en 12 horas.\n\n**Pregunta para debate:** Si fueras el asesor de seguridad del hospital, ¿recomendarías pagar el rescate inmediatamente o rechazarías el pago priorizando la política de seguridad a largo plazo?',
    NULL,
    (SELECT id FROM public.categories WHERE slug = 'ciberseguridad'),
    true
)
ON CONFLICT DO NOTHING;
