# Generated by Django 6.0.5 on 2026-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_proyectoauditoria_riesgodetectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
